
package essai2;

import javax.swing.JDesktopPane;


public class Fen extends javax.swing.JFrame {

    
    private IF_Editeur ifEditeur;
    private IF_A_Editeur ifAEditeur;
    
    private IF_Langue ifLangue;
    private IF_A_Langue ifALangue;
    
    private IF_Auteur ifAuteur;
    private IF_A_Auteur ifAAuteur;
    
    private IF_Theme ifTheme;
    private IF_A_Theme ifATheme;
    
            
    public Fen() {
        initComponents();
        
        ifEditeur=new IF_Editeur();
        DP_Integration.add(ifEditeur);
        ifEditeur.setFen(this);
        
        ifAEditeur=new IF_A_Editeur();
        DP_Affichage.add(ifAEditeur);
        ifAEditeur.setFen(this);
        
        ifLangue=new IF_Langue();
        DP_Integration.add(ifLangue);
        ifLangue.setFen(this);
        
        ifALangue=new IF_A_Langue();
        DP_Affichage.add(ifALangue);
        ifALangue.setFen(this);
        
        ifAuteur=new IF_Auteur();
        DP_Integration.add(ifAuteur);
        ifAuteur.setFen(this);
        
        ifAAuteur=new IF_A_Auteur();
        DP_Affichage.add(ifAAuteur);
        ifAAuteur.setFen(this);
        
        ifTheme=new IF_Theme();
        DP_Integration.add(ifTheme);
        ifTheme.setFen(this);
        
        ifATheme=new IF_A_Theme();
        DP_Affichage.add(ifATheme);
        ifATheme.setFen(this);
        
    }

    public JDesktopPane getDP_Integration() {
        return DP_Integration;
    }

    public JDesktopPane getDP_Affichage() {
        return DP_Affichage;
    }

    public IF_Editeur getIfEditeur() {
        return ifEditeur;
    }

    public IF_A_Editeur getIfAEditeur() {
        return ifAEditeur;
    }

    public IF_Langue getIfLangue() {
        return ifLangue;
    }

    public IF_A_Langue getIfALangue() {
        return ifALangue;
    }

    public IF_Auteur getIfAuteur() {
        return ifAuteur;
    }

    public IF_A_Auteur getIfAAuteur() {
        return ifAAuteur;
    }

    public IF_Theme getIfTheme() {
        return ifTheme;
    }

    public IF_A_Theme getIfATheme() {
        return ifATheme;
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_Global = new javax.swing.JPanel();
        P_Central = new javax.swing.JPanel();
        P_Footer = new javax.swing.JPanel();
        L_Afpa = new javax.swing.JLabel();
        P_Header = new javax.swing.JPanel();
        L_Librairie = new javax.swing.JLabel();
        P_Body = new javax.swing.JPanel();
        P_Menu = new javax.swing.JPanel();
        B_Livre = new javax.swing.JButton();
        B_Editeur = new javax.swing.JButton();
        B_Auteur = new javax.swing.JButton();
        B_Langue = new javax.swing.JButton();
        B_Theme = new javax.swing.JButton();
        B_SSTheme = new javax.swing.JButton();
        B_Rubrique = new javax.swing.JButton();
        B_MotCle = new javax.swing.JButton();
        DP_Integration = new javax.swing.JDesktopPane();
        DP_Affichage = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRAIRIE");
        setBackground(new java.awt.Color(204, 204, 255));
        setExtendedState(MAXIMIZED_BOTH);

        P_Global.setForeground(new java.awt.Color(255, 255, 255));

        P_Central.setBackground(new java.awt.Color(153, 204, 255));
        P_Central.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 4, true));
        P_Central.setForeground(new java.awt.Color(153, 204, 255));

        P_Footer.setBackground(new java.awt.Color(255, 255, 255));
        P_Footer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 1, true));
        P_Footer.setForeground(new java.awt.Color(0, 0, 153));

        L_Afpa.setFont(new java.awt.Font("Magneto", 1, 30)); // NOI18N
        L_Afpa.setForeground(new java.awt.Color(0, 102, 153));
        L_Afpa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Afpa.setText("AFPA CDI");

        javax.swing.GroupLayout P_FooterLayout = new javax.swing.GroupLayout(P_Footer);
        P_Footer.setLayout(P_FooterLayout);
        P_FooterLayout.setHorizontalGroup(
            P_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Afpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        P_FooterLayout.setVerticalGroup(
            P_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Afpa)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        P_Header.setBackground(new java.awt.Color(255, 255, 255));
        P_Header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        L_Librairie.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        L_Librairie.setForeground(new java.awt.Color(0, 0, 102));
        L_Librairie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Librairie.setText("LIBRAIRIE");

        javax.swing.GroupLayout P_HeaderLayout = new javax.swing.GroupLayout(P_Header);
        P_Header.setLayout(P_HeaderLayout);
        P_HeaderLayout.setHorizontalGroup(
            P_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Librairie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        P_HeaderLayout.setVerticalGroup(
            P_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Librairie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        P_Body.setBackground(new java.awt.Color(255, 255, 255));
        P_Body.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 1, true));
        P_Body.setForeground(new java.awt.Color(0, 0, 153));

        P_Menu.setBackground(new java.awt.Color(255, 255, 255));
        P_Menu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 1, true), "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Showcard Gothic", 1, 28), new java.awt.Color(0, 0, 153))); // NOI18N

        B_Livre.setBackground(new java.awt.Color(204, 255, 204));
        B_Livre.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        B_Livre.setForeground(new java.awt.Color(51, 0, 153));
        B_Livre.setText("Livre");
        B_Livre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        B_Editeur.setBackground(new java.awt.Color(204, 255, 204));
        B_Editeur.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        B_Editeur.setForeground(new java.awt.Color(51, 0, 153));
        B_Editeur.setText("Editeur");
        B_Editeur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_Editeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EditeurActionPerformed(evt);
            }
        });

        B_Auteur.setBackground(new java.awt.Color(204, 255, 204));
        B_Auteur.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        B_Auteur.setForeground(new java.awt.Color(51, 0, 153));
        B_Auteur.setText("Auteur");
        B_Auteur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_Auteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AuteurActionPerformed(evt);
            }
        });

        B_Langue.setBackground(new java.awt.Color(204, 255, 204));
        B_Langue.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        B_Langue.setForeground(new java.awt.Color(51, 0, 153));
        B_Langue.setText("Langue");
        B_Langue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_Langue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LangueActionPerformed(evt);
            }
        });

        B_Theme.setBackground(new java.awt.Color(204, 255, 204));
        B_Theme.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        B_Theme.setForeground(new java.awt.Color(51, 0, 153));
        B_Theme.setText("Thème");
        B_Theme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_Theme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ThemeActionPerformed(evt);
            }
        });

        B_SSTheme.setBackground(new java.awt.Color(204, 255, 204));
        B_SSTheme.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        B_SSTheme.setForeground(new java.awt.Color(51, 0, 153));
        B_SSTheme.setText("Sous-Thème");
        B_SSTheme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        B_Rubrique.setBackground(new java.awt.Color(204, 255, 204));
        B_Rubrique.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        B_Rubrique.setForeground(new java.awt.Color(51, 0, 153));
        B_Rubrique.setText("Rubrique");
        B_Rubrique.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        B_MotCle.setBackground(new java.awt.Color(204, 255, 204));
        B_MotCle.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        B_MotCle.setForeground(new java.awt.Color(51, 0, 153));
        B_MotCle.setText("Mot-Clé");
        B_MotCle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout P_MenuLayout = new javax.swing.GroupLayout(P_Menu);
        P_Menu.setLayout(P_MenuLayout);
        P_MenuLayout.setHorizontalGroup(
            P_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_Livre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Editeur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_SSTheme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Theme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Langue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Auteur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Rubrique, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_MotCle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        P_MenuLayout.setVerticalGroup(
            P_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B_Livre)
                .addGap(18, 18, 18)
                .addComponent(B_Auteur)
                .addGap(18, 18, 18)
                .addComponent(B_Editeur)
                .addGap(18, 18, 18)
                .addComponent(B_Langue)
                .addGap(18, 18, 18)
                .addComponent(B_Theme)
                .addGap(18, 18, 18)
                .addComponent(B_SSTheme)
                .addGap(18, 18, 18)
                .addComponent(B_Rubrique)
                .addGap(18, 18, 18)
                .addComponent(B_MotCle)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout P_BodyLayout = new javax.swing.GroupLayout(P_Body);
        P_Body.setLayout(P_BodyLayout);
        P_BodyLayout.setHorizontalGroup(
            P_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_BodyLayout.setVerticalGroup(
            P_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout P_CentralLayout = new javax.swing.GroupLayout(P_Central);
        P_Central.setLayout(P_CentralLayout);
        P_CentralLayout.setHorizontalGroup(
            P_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P_Footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P_Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_CentralLayout.setVerticalGroup(
            P_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CentralLayout.createSequentialGroup()
                .addComponent(P_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout DP_IntegrationLayout = new javax.swing.GroupLayout(DP_Integration);
        DP_Integration.setLayout(DP_IntegrationLayout);
        DP_IntegrationLayout.setHorizontalGroup(
            DP_IntegrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        DP_IntegrationLayout.setVerticalGroup(
            DP_IntegrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DP_AffichageLayout = new javax.swing.GroupLayout(DP_Affichage);
        DP_Affichage.setLayout(DP_AffichageLayout);
        DP_AffichageLayout.setHorizontalGroup(
            DP_AffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        DP_AffichageLayout.setVerticalGroup(
            DP_AffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout P_GlobalLayout = new javax.swing.GroupLayout(P_Global);
        P_Global.setLayout(P_GlobalLayout);
        P_GlobalLayout.setHorizontalGroup(
            P_GlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_GlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DP_Integration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_Central, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DP_Affichage)
                .addContainerGap())
        );
        P_GlobalLayout.setVerticalGroup(
            P_GlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_GlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_GlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DP_Affichage)
                    .addGroup(P_GlobalLayout.createSequentialGroup()
                        .addGroup(P_GlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DP_Integration)
                            .addComponent(P_Central, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Global, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Global, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_EditeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EditeurActionPerformed
        // TODO add your handling code here:
        if (ifEditeur.isClosed()) {
            DP_Integration.getDesktopManager().closeFrame(ifEditeur);
            DP_Integration.add(ifEditeur);
        }
        ifEditeur.setVisible(true);
        
         if (ifAEditeur.isClosed()) {
            DP_Affichage.getDesktopManager().closeFrame(ifAEditeur);
            DP_Affichage.add(ifAEditeur);
        }
        ifAEditeur.setVisible(true);
    }//GEN-LAST:event_B_EditeurActionPerformed

    private void B_LangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LangueActionPerformed
        // TODO add your handling code here:
        if (ifLangue.isClosed()) {
            DP_Integration.getDesktopManager().closeFrame(ifLangue);
            DP_Integration.add(ifLangue);
        }
        ifLangue.setVisible(true);
        
         if (ifALangue.isClosed()) {
            DP_Affichage.getDesktopManager().closeFrame(ifALangue);
            DP_Affichage.add(ifALangue);
        }
        ifALangue.setVisible(true);
        
    }//GEN-LAST:event_B_LangueActionPerformed

    private void B_AuteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AuteurActionPerformed
        // TODO add your handling code here:
        if (ifAuteur.isClosed()) {
            DP_Integration.getDesktopManager().closeFrame(ifAuteur);
            DP_Integration.add(ifAuteur);
        }
        ifAuteur.setVisible(true);
        
         if (ifAAuteur.isClosed()) {
            DP_Affichage.getDesktopManager().closeFrame(ifAAuteur);
            DP_Affichage.add(ifAAuteur);
        }
        ifAAuteur.setVisible(true);
    }//GEN-LAST:event_B_AuteurActionPerformed

    private void B_ThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ThemeActionPerformed
        // TODO add your handling code here:
        if (ifTheme.isClosed()) {
            DP_Integration.getDesktopManager().closeFrame(ifTheme);
            DP_Integration.add(ifTheme);
        }
        ifTheme.setVisible(true);
        
         if (ifATheme.isClosed()) {
            DP_Affichage.getDesktopManager().closeFrame(ifATheme);
            DP_Affichage.add(ifATheme);
        }
        ifATheme.setVisible(true);
    }//GEN-LAST:event_B_ThemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Auteur;
    private javax.swing.JButton B_Editeur;
    private javax.swing.JButton B_Langue;
    private javax.swing.JButton B_Livre;
    private javax.swing.JButton B_MotCle;
    private javax.swing.JButton B_Rubrique;
    private javax.swing.JButton B_SSTheme;
    private javax.swing.JButton B_Theme;
    private javax.swing.JDesktopPane DP_Affichage;
    private javax.swing.JDesktopPane DP_Integration;
    private javax.swing.JLabel L_Afpa;
    private javax.swing.JLabel L_Librairie;
    private javax.swing.JPanel P_Body;
    private javax.swing.JPanel P_Central;
    private javax.swing.JPanel P_Footer;
    private javax.swing.JPanel P_Global;
    private javax.swing.JPanel P_Header;
    private javax.swing.JPanel P_Menu;
    // End of variables declaration//GEN-END:variables
}
