/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package essai2;

/**
 *
 * @author HP
 */
public class IF_A_Livre extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_A_Livre
     */
    public IF_A_Livre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTableLivre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivre = new javax.swing.JTable();
        panelRechercheLivre = new javax.swing.JPanel();
        txtRecherche = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("LIVRES");

        panelTableLivre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tableau Livre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelTableLivre.setLayout(new java.awt.GridBagLayout());

        jTableLivre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLivre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLivreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLivre);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 770;
        gridBagConstraints.ipady = 356;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 16, 18, 16);
        panelTableLivre.add(jScrollPane1, gridBagConstraints);

        panelRechercheLivre.setBorder(javax.swing.BorderFactory.createTitledBorder("Recherche"));
        panelRechercheLivre.setLayout(new java.awt.GridBagLayout());

        txtRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRechercheMouseClicked(evt);
            }
        });
        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRechercheKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 232;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 16, 23, 16);
        panelRechercheLivre.add(txtRecherche, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTableLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 833, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelRechercheLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRechercheLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTableLivre, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivreMouseClicked
        try {
            int row = jTableLivre.getSelectedRow();
            String Table_click = (jTableLivre.getModel().getValueAt(row, 0).toString());
            String req = "SELECT idEditeur, nomEditeur,"
            + " noRueEditeur, rueEditeur,"
            + " codePostalEditeur, villeEditeur,"
            + " paysEditeur,  telephoneEditeur,"
            + " emailEditeur, supprimeEditeur"
            + " from Editeur WHERE IdEditeur='" + Table_click + "' ";
            ResultSet rs = livre.selectionner(req);
            if (rs.next()) {
                String add1 = rs.getString("isbnLivre");
                txtISBN.setText(add1);
                String add2 = rs.getString("nomEditeur");
                txtnom.setText(add2);
                String add3 = rs.getString("noRueEditeur");
                txtnrue.setText(add3);
                String add4 = rs.getString("rueEditeur");
                txtrue.setText(add4);
                String add5 = rs.getString("codePostalEditeur");
                txtcodePostal.setText(add5);
                String add6 = rs.getString("villeEditeur");
                txtville.setText(add6);
                String add7 = rs.getString("paysEditeur");
                txtpays.setText(add7);
                String add8 = rs.getString("telephoneEditeur");
                txttel.setText(add8);
                String add9 = rs.getString("emailEditeur");
                txtemail.setText(add9);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jTableLivreMouseClicked

    private void txtRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRechercheMouseClicked

    }//GEN-LAST:event_txtRechercheMouseClicked

    private void txtRechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheKeyPressed

    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
        // TODO add your handling code here:

        try{
            String req="SELECT idEditeur AS ID, nomEditeur AS NOM,"
            + " noRueEditeur AS NUM, rueEditeur AS RUE,"
            + " codePostalEditeur AS CP, villeEditeur AS VILLE,"
            + " paysEditeur AS PAYS,  telephoneEditeur AS TEL,"
            + " emailEditeur AS EMAIL, supprimeEditeur AS SUPPR"
            + " from Editeur"
            + " where nomEditeur+telephoneEditeur+emailEditeur+villeEditeur+codePostalEditeur like ?";
            ResultSet rs = livre.rechercher(req,"%"+txtRecherche.getText()+"%");
            jTableLivre.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtRechercheKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivre;
    private javax.swing.JPanel panelRechercheLivre;
    private javax.swing.JPanel panelTableLivre;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
