/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package essai2;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;



public class IF_A_Editeur extends javax.swing.JInternalFrame {

   
    private Editeur editeur=new Editeur();
    private Fen fen;
    
    public IF_A_Editeur() {
        initComponents();
    }

    public void setFen(Fen fen) {
        this.fen = fen;
    }

    public JTable getjTableEditeur() {
        return jTableEditeur;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTableEditeur = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEditeur = new javax.swing.JTable();
        panelRecherche = new javax.swing.JPanel();
        txtRecherche = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EDITEURS");

        panelTableEditeur.setBackground(new java.awt.Color(255, 255, 255));
        panelTableEditeur.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editeurs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTableEditeur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "NUM", "RUE", "CP", "VILLE", "PAYS", "TEL", "EMAIL", "ACTIF"
            }
        ));
        jTableEditeur.setSelectionForeground(new java.awt.Color(204, 255, 255));
        jTableEditeur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEditeurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEditeur);

        javax.swing.GroupLayout panelTableEditeurLayout = new javax.swing.GroupLayout(panelTableEditeur);
        panelTableEditeur.setLayout(panelTableEditeurLayout);
        panelTableEditeurLayout.setHorizontalGroup(
            panelTableEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableEditeurLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTableEditeurLayout.setVerticalGroup(
            panelTableEditeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableEditeurLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        panelRecherche.setBorder(javax.swing.BorderFactory.createTitledBorder("Recherche"));
        panelRecherche.setLayout(new java.awt.GridBagLayout());

        txtRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRechercheMouseClicked(evt);
            }
        });
        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRechercheKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 232;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 16, 23, 16);
        panelRecherche.add(txtRecherche, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTableEditeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTableEditeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableEditeurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEditeurMouseClicked
        try {
            int row = jTableEditeur.getSelectedRow();
            String Table_click = (jTableEditeur.getModel().getValueAt(row, 0).toString());
            String req = "SELECT idEditeur, nomEditeur,"
            + " noRueEditeur, rueEditeur,"
            + " codePostalEditeur, villeEditeur,"
            + " paysEditeur,  telephoneEditeur,"
            + " emailEditeur, actifEditeur"
            + " from Editeur WHERE IdEditeur='" + Table_click + "' ";
            ResultSet rs = editeur.selectionner(req);
            if (rs.next()) {
                String add1 = rs.getString("idEditeur");
                fen.getIfEditeur().getTxtId().setText(add1);
                String add2 = rs.getString("nomEditeur");
                fen.getIfEditeur().getTxtnom().setText(add2);
                String add3 = rs.getString("noRueEditeur");
                fen.getIfEditeur().getTxtnrue().setText(add3);
                String add4 = rs.getString("rueEditeur");
                fen.getIfEditeur().getTxtrue().setText(add4);
                String add5 = rs.getString("codePostalEditeur");
                fen.getIfEditeur().getTxtcodePostal().setText(add5);
                String add6 = rs.getString("villeEditeur");
                fen.getIfEditeur().getTxtville().setText(add6);
                String add7 = rs.getString("paysEditeur");
                fen.getIfEditeur().getTxtpays().setText(add7);
                String add8 = rs.getString("telephoneEditeur");
                fen.getIfEditeur().getTxttel().setText(add8);
                String add9 = rs.getString("emailEditeur");
                fen.getIfEditeur().getTxtemail().setText(add9);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jTableEditeurMouseClicked

    private void txtRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRechercheMouseClicked

    }//GEN-LAST:event_txtRechercheMouseClicked

    private void txtRechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheKeyPressed

    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
        // TODO add your handling code here:

        try{
            String req="SELECT idEditeur AS ID, nomEditeur AS NOM,"
            + " noRueEditeur AS NUM, rueEditeur AS RUE,"
            + " codePostalEditeur AS CP, villeEditeur AS VILLE,"
            + " paysEditeur AS PAYS,  telephoneEditeur AS TEL,"
            + " emailEditeur AS EMAIL, actifEditeur AS ACTIF"
            + " from Editeur"
            + " where nomEditeur+telephoneEditeur like ?";
            ResultSet rs = editeur.rechercher(req,"%"+txtRecherche.getText()+"%");
            jTableEditeur.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtRechercheKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEditeur;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JPanel panelTableEditeur;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
