package essai2;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class IF_A_Theme extends javax.swing.JInternalFrame {

    private Theme theme=new Theme();
    private Fen fen;
    
    public IF_A_Theme() {
        initComponents();
    }

    public JTable getjTableTheme() {
        return jTableTheme;
    }

    public JTextField getTxtRecherche() {
        return txtRecherche;
    }

    public void setFen(Fen fen) {
        this.fen = fen;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelRechercheLangue = new javax.swing.JPanel();
        txtRecherche = new javax.swing.JTextField();
        panelTableTheme = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTheme = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("THEMES");

        panelRechercheLangue.setBorder(javax.swing.BorderFactory.createTitledBorder("Recherche"));
        panelRechercheLangue.setLayout(new java.awt.GridBagLayout());

        txtRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRechercheMouseClicked(evt);
            }
        });
        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRechercheKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 232;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 16, 23, 16);
        panelRechercheLangue.add(txtRecherche, gridBagConstraints);

        panelTableTheme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thèmes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelTableTheme.setLayout(new java.awt.GridBagLayout());

        jTableTheme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "THEME", "ACTIF"
            }
        ));
        jTableTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableThemeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTheme);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 770;
        gridBagConstraints.ipady = 356;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 16, 18, 16);
        panelTableTheme.add(jScrollPane1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRechercheLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTableTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRechercheLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTableTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRechercheMouseClicked

    }//GEN-LAST:event_txtRechercheMouseClicked

    private void txtRechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheKeyPressed

    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
        // TODO add your handling code here:

        try{
            String req = "SELECT idTheme AS ID, nomTheme AS THEME,actifTheme AS ACTIF"
            + " from Theme"
            + " where nomTheme like ?";
            ResultSet rs = theme.rechercher(req,"%"+txtRecherche.getText()+"%");
            jTableTheme.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtRechercheKeyReleased

    private void jTableThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableThemeMouseClicked
        try {
            int row = jTableTheme.getSelectedRow();
            String Table_click = (jTableTheme.getModel().getValueAt(row, 0).toString());
            String req = "SELECT idTheme, nomTheme,actifTheme"
            + " from Theme WHERE IdTheme='" + Table_click + "' ";
            ResultSet rs = theme.selectionner(req);
            if (rs.next()) {
                String add1 = rs.getString("idTheme");
                fen.getIfTheme().getTxtId().setText(add1);
                String add2 = rs.getString("nomTheme");
                fen.getIfTheme().getTxtTheme().setText(add2);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jTableThemeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTheme;
    private javax.swing.JPanel panelRechercheLangue;
    private javax.swing.JPanel panelTableTheme;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
