package essai2;

import java.util.Date;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class IF_A_Auteur extends javax.swing.JInternalFrame {

    private Auteur auteur=new Auteur();
    private Fen fen;
    
    
    public IF_A_Auteur() {
        initComponents();
    }

    public void setFen(Fen fen) {
        this.fen = fen;
    }

    public JTable getjTableAuteur() {
        return jTableAuteur;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelRecherche = new javax.swing.JPanel();
        txtRecherche = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAuteur = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("AUTEURS");

        panelRecherche.setBorder(javax.swing.BorderFactory.createTitledBorder("Recherche"));
        panelRecherche.setLayout(new java.awt.GridBagLayout());

        txtRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRechercheMouseClicked(evt);
            }
        });
        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRechercheKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 232;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 16, 23, 16);
        panelRecherche.add(txtRecherche, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Auteurs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTableAuteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "PRENOM", "DATE", "LIEU", "ACTIF"
            }
        ));
        jTableAuteur.setSelectionForeground(new java.awt.Color(204, 255, 255));
        jTableAuteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAuteurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAuteur);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAuteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAuteurMouseClicked
        try {
            int row = jTableAuteur.getSelectedRow();
            String Table_click = (jTableAuteur.getModel().getValueAt(row, 0).toString());
            String req = "SELECT idAuteur, nomAuteur,"
            + " prenomAuteur, dateNaissanceAuteur,"
            + " lieuNaissanceAuteur, actifAuteur"
            + " from Auteur WHERE IdAuteur='" + Table_click + "' ";
            ResultSet rs = auteur.selectionner(req);
            if (rs.next()) {
                String add1 = rs.getString("idAuteur");
                fen.getIfAuteur().getTxtId().setText(add1);
                String add2 = rs.getString("nomAuteur");
                fen.getIfAuteur().getTxtnom().setText(add2);
                String add3 = rs.getString("prenomAuteur");
                fen.getIfAuteur().getTxtPrenom().setText(add3);
                Date add4 = rs.getDate("dateNaissanceAuteur");
                fen.getIfAuteur().getChooserDateNaissance().setDate(add4);
                String add5 = rs.getString("lieuNaissanceAuteur");
                fen.getIfAuteur().getTxtLieuNaissance().setText(add5);
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jTableAuteurMouseClicked

    private void txtRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRechercheMouseClicked

    }//GEN-LAST:event_txtRechercheMouseClicked

    private void txtRechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheKeyPressed

    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
        // TODO add your handling code here:

        try{
            String req="SELECT idAuteur AS ID, nomAuteur AS NOM,"
                    + " prenomAuteur AS PRENOM, dateNaissanceAuteur AS NAISS,"
                    + " lieuNaissanceAuteur AS LIEU, actifAuteur AS ACTIF"
                    + " from Auteur"
            + " where nomAuteur+prenomAuteur+lieuNaissanceAuteur like ?";
            ResultSet rs = auteur.rechercher(req,"%"+txtRecherche.getText()+"%");
            jTableAuteur.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtRechercheKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAuteur;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
