package essai2;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class IF_Editeur extends javax.swing.JInternalFrame {

    private Editeur editeur=new Editeur();
    private Fen fen;
    
    public IF_Editeur() {
        initComponents();
    }

    public void setFen(Fen fen) {
        this.fen = fen;
    }

    public JLabel getTxtId() {
        return txtId;
    }

    public JTextField getTxtcodePostal() {
        return txtcodePostal;
    }

    public JTextField getTxtnom() {
        return txtnom;
    }

    public JTextField getTxtnrue() {
        return txtnrue;
    }

    public JTextField getTxtpays() {
        return txtpays;
    }

    public JTextField getTxtrue() {
        return txtrue;
    }

    public JTextField getTxttel() {
        return txttel;
    }

    public JTextField getTxtville() {
        return txtville;
    }

    public JTextField getTxtemail() {
        return txtemail;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChampsEditeur = new javax.swing.JPanel();
        lblnom = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        lblnrue = new javax.swing.JLabel();
        txtnrue = new javax.swing.JTextField();
        lblrue = new javax.swing.JLabel();
        txtrue = new javax.swing.JTextField();
        lblpays = new javax.swing.JLabel();
        txtpays = new javax.swing.JTextField();
        lbltel = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        lblcodePostal = new javax.swing.JLabel();
        txtcodePostal = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        lblville1 = new javax.swing.JLabel();
        txtville = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        panelBoutons = new javax.swing.JPanel();
        jButtonInserer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonAfficher = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EDITEUR");

        panelChampsEditeur.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editeur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelChampsEditeur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnom.setText("Nom: ");
        panelChampsEditeur.add(lblnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        txtnom.setColumns(20);
        panelChampsEditeur.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        lblnrue.setText("N° Rue: ");
        panelChampsEditeur.add(lblnrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        txtnrue.setColumns(2);
        panelChampsEditeur.add(txtnrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 40, -1));

        lblrue.setText("Rue: ");
        panelChampsEditeur.add(lblrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtrue.setColumns(20);
        panelChampsEditeur.add(txtrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 30));

        lblpays.setText("Pays: ");
        panelChampsEditeur.add(lblpays, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        txtpays.setColumns(20);
        panelChampsEditeur.add(txtpays, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        lbltel.setText("Téléphone: ");
        panelChampsEditeur.add(lbltel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        txttel.setColumns(20);
        panelChampsEditeur.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        lblcodePostal.setText("Code Postal:");
        panelChampsEditeur.add(lblcodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        txtcodePostal.setColumns(20);
        panelChampsEditeur.add(txtcodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtemail.setColumns(20);
        panelChampsEditeur.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        lblemail.setText("E-mail: ");
        panelChampsEditeur.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        lblville1.setText("Ville: ");
        panelChampsEditeur.add(lblville1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        txtville.setColumns(20);
        panelChampsEditeur.add(txtville, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel1.setText("Id:");
        panelChampsEditeur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelChampsEditeur.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 30, 20));

        panelBoutons.setBorder(javax.swing.BorderFactory.createTitledBorder("Boutons"));
        panelBoutons.setLayout(new java.awt.GridBagLayout());

        jButtonInserer.setText("Insérer");
        jButtonInserer.setAlignmentX(0.5F);
        jButtonInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsererActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonInserer, new java.awt.GridBagConstraints());

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonModifier, new java.awt.GridBagConstraints());

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonSupprimer, new java.awt.GridBagConstraints());

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonAfficher, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelChampsEditeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBoutons, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChampsEditeur, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void afficherTable() throws SQLException, Exception {

        try {
            String req = "SELECT idEditeur AS ID, nomEditeur AS NOM,"
                    + " noRueEditeur AS NUM, rueEditeur AS RUE,"
                    + " codePostalEditeur AS CP, villeEditeur AS VILLE,"
                    + " paysEditeur AS PAYS,  telephoneEditeur AS TEL,"
                    + " emailEditeur AS EMAIL, actifEditeur AS ACTIF"
                    + " from Editeur";
            ResultSet rs = editeur.selectionner(req);
            fen.getIfAEditeur().getjTableEditeur().setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    private void jButtonInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsererActionPerformed

        try {
            editeur.setNom(txtnom.getText());
            editeur.setNoRue(txtnrue.getText());
            editeur.setRue(txtrue.getText());
            editeur.setCodePostal(txtcodePostal.getText());
            editeur.setVille(txtville.getText());
            editeur.setPays(txtpays.getText());
            editeur.setTelephone(txttel.getText());
            editeur.setEmail(txtemail.getText());
            editeur.getActif();

        } catch (Exception ex) {
            
        }

        try {
            editeur.inserer();
            afficherTable();
        } catch (ClassNotFoundException ex) {
           
        } catch (SQLException ex) {
           
        } catch (Exception ex) {
            
        }

        System.out.println("Données insérées.");

    }//GEN-LAST:event_jButtonInsererActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        try {
            editeur.setNom(txtnom.getText());
            editeur.setNoRue(txtnrue.getText());
            editeur.setRue(txtrue.getText());
            editeur.setCodePostal(txtcodePostal.getText());
            editeur.setVille(txtville.getText());
            editeur.setPays(txtpays.getText());
            editeur.setTelephone(txttel.getText());
            editeur.setEmail(txtemail.getText());
            editeur.getActif();
            System.out.println("id: " + Integer.parseInt(txtId.getText()));
            editeur.modifier(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {
            
        }

        System.out.println("Données modifiées.");

    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        try {
            editeur.supprimer(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {
            
        }

        System.out.println("Données supprimées.");

    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherActionPerformed
        try {
            afficherTable();
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jButtonAfficherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonInserer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcodePostal;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lblnrue;
    private javax.swing.JLabel lblpays;
    private javax.swing.JLabel lblrue;
    private javax.swing.JLabel lbltel;
    private javax.swing.JLabel lblville1;
    private javax.swing.JPanel panelBoutons;
    private javax.swing.JPanel panelChampsEditeur;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtcodePostal;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnrue;
    private javax.swing.JTextField txtpays;
    private javax.swing.JTextField txtrue;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtville;
    // End of variables declaration//GEN-END:variables
}
