/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package essai2;

/**
 *
 * @author HP
 */
public class IF_Livre extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_Livre
     */
    public IF_Livre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLivre = new javax.swing.JPanel();
        panelDetails = new javax.swing.JPanel();
        panelTitre = new javax.swing.JPanel();
        lblsousTitre = new javax.swing.JLabel();
        txtsousTitre = new javax.swing.JTextField();
        lbltitre = new javax.swing.JLabel();
        txttitre = new javax.swing.JTextField();
        panelTheme = new javax.swing.JPanel();
        lblTheme = new javax.swing.JLabel();
        combotheme = new javax.swing.JComboBox();
        lblSousTheme = new javax.swing.JLabel();
        combosstheme = new javax.swing.JComboBox();
        ajouterTheme = new javax.swing.JButton();
        ajouterSousTheme = new javax.swing.JButton();
        panelAuteur = new javax.swing.JPanel();
        lblAuteur = new javax.swing.JLabel();
        comboAuteur = new javax.swing.JComboBox();
        ajouterAuteur = new javax.swing.JButton();
        panelStock = new javax.swing.JPanel();
        lblstock = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        panelResume = new javax.swing.JPanel();
        lblresume = new javax.swing.JLabel();
        scpresume = new javax.swing.JScrollPane();
        txtresume = new javax.swing.JTextArea();
        panelPrix = new javax.swing.JPanel();
        lblprixHT = new javax.swing.JLabel();
        txtprixHT = new javax.swing.JTextField();
        panelTVA = new javax.swing.JPanel();
        lblTVA = new javax.swing.JLabel();
        txtTVA = new javax.swing.JTextField();
        panelLangue = new javax.swing.JPanel();
        lbllangue = new javax.swing.JLabel();
        comboLangue = new javax.swing.JComboBox();
        ajouterLangue = new javax.swing.JButton();
        panelEdition = new javax.swing.JPanel();
        lbldateEdition = new javax.swing.JLabel();
        chooserDateEdition = new com.toedter.calendar.JDateChooser();
        lblediteur = new javax.swing.JLabel();
        comboEditeur = new javax.swing.JComboBox();
        ajouterEditeur = new javax.swing.JButton();
        panelImage = new javax.swing.JPanel();
        panelAffichageImage = new javax.swing.JPanel();
        panelFichier = new javax.swing.JPanel();
        chooserImage = new javax.swing.JFileChooser();
        panelISBN = new javax.swing.JPanel();
        lblNumISBN = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        panelBoutonsLivre = new javax.swing.JPanel();
        jButtonInserer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonAfficher = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("LIVRE");

        panelLivre.setBorder(javax.swing.BorderFactory.createTitledBorder("Livre"));

        panelDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Détails"));

        panelTitre.setBorder(javax.swing.BorderFactory.createTitledBorder("Titre"));

        lblsousTitre.setText("Sous-titre: ");

        txtsousTitre.setColumns(20);
        txtsousTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsousTitreActionPerformed(evt);
            }
        });

        lbltitre.setText("Titre: ");

        txttitre.setColumns(20);
        txttitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttitreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTitreLayout = new javax.swing.GroupLayout(panelTitre);
        panelTitre.setLayout(panelTitreLayout);
        panelTitreLayout.setHorizontalGroup(
            panelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTitreLayout.createSequentialGroup()
                        .addComponent(lblsousTitre)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitreLayout.createSequentialGroup()
                        .addComponent(lbltitre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttitre, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(txtsousTitre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitreLayout.setVerticalGroup(
            panelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltitre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsousTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTitreLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblsousTitre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTheme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thème", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblTheme.setText("Thème:");

        combotheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSousTheme.setText("Sous-thème:");

        combosstheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ajouterTheme.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajouterTheme.setText("+");
        ajouterTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterThemeActionPerformed(evt);
            }
        });

        ajouterSousTheme.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajouterSousTheme.setText("+");
        ajouterSousTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterSousThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThemeLayout = new javax.swing.GroupLayout(panelTheme);
        panelTheme.setLayout(panelThemeLayout);
        panelThemeLayout.setHorizontalGroup(
            panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelThemeLayout.createSequentialGroup()
                        .addComponent(lblTheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combotheme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThemeLayout.createSequentialGroup()
                        .addComponent(lblSousTheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combosstheme, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajouterSousTheme)
                    .addComponent(ajouterTheme))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelThemeLayout.setVerticalGroup(
            panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTheme)
                    .addComponent(combotheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSousTheme)
                    .addComponent(combosstheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterSousTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        panelAuteur.setBorder(javax.swing.BorderFactory.createTitledBorder("Auteur"));

        lblAuteur.setText("Auteur:");

        comboAuteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ajouterAuteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajouterAuteur.setText("+");
        ajouterAuteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterAuteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAuteurLayout = new javax.swing.GroupLayout(panelAuteur);
        panelAuteur.setLayout(panelAuteurLayout);
        panelAuteurLayout.setHorizontalGroup(
            panelAuteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuteurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAuteur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ajouterAuteur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAuteurLayout.setVerticalGroup(
            panelAuteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuteurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAuteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuteur)
                    .addComponent(comboAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));

        lblstock.setText("Stock: ");

        txtstock.setColumns(20);
        txtstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStockLayout = new javax.swing.GroupLayout(panelStock);
        panelStock.setLayout(panelStockLayout);
        panelStockLayout.setHorizontalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblstock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStockLayout.setVerticalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstock)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelResume.setBorder(javax.swing.BorderFactory.createTitledBorder("Résumé"));

        lblresume.setText("Résumé: ");

        txtresume.setColumns(51);
        txtresume.setRows(5);
        txtresume.setFocusCycleRoot(true);
        scpresume.setViewportView(txtresume);

        javax.swing.GroupLayout panelResumeLayout = new javax.swing.GroupLayout(panelResume);
        panelResume.setLayout(panelResumeLayout);
        panelResumeLayout.setHorizontalGroup(
            panelResumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblresume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpresume, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResumeLayout.setVerticalGroup(
            panelResumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumeLayout.createSequentialGroup()
                .addComponent(scpresume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(panelResumeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblresume)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrix.setBorder(javax.swing.BorderFactory.createTitledBorder("Prix"));

        lblprixHT.setText("Prix (HT): ");

        txtprixHT.setColumns(20);
        txtprixHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprixHTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrixLayout = new javax.swing.GroupLayout(panelPrix);
        panelPrix.setLayout(panelPrixLayout);
        panelPrixLayout.setHorizontalGroup(
            panelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblprixHT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtprixHT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrixLayout.setVerticalGroup(
            panelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrixLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprixHT)
                    .addComponent(txtprixHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTVA.setBorder(javax.swing.BorderFactory.createTitledBorder("TVA"));

        lblTVA.setText("TVA: ");

        txtTVA.setColumns(20);
        txtTVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTVAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTVALayout = new javax.swing.GroupLayout(panelTVA);
        panelTVA.setLayout(panelTVALayout);
        panelTVALayout.setHorizontalGroup(
            panelTVALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTVALayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblTVA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTVALayout.setVerticalGroup(
            panelTVALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTVALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTVALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTVA))
                .addContainerGap())
        );

        panelLangue.setBorder(javax.swing.BorderFactory.createTitledBorder("Langue"));

        lbllangue.setText("Langue: ");

        comboLangue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboLangue.setPreferredSize(new java.awt.Dimension(165, 20));
        comboLangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLangueActionPerformed(evt);
            }
        });

        ajouterLangue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajouterLangue.setText("+");
        ajouterLangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterLangueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLangueLayout = new javax.swing.GroupLayout(panelLangue);
        panelLangue.setLayout(panelLangueLayout);
        panelLangueLayout.setHorizontalGroup(
            panelLangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLangueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllangue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajouterLangue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLangueLayout.setVerticalGroup(
            panelLangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLangueLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelLangueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllangue)
                    .addComponent(comboLangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelEdition.setBorder(javax.swing.BorderFactory.createTitledBorder("Edition"));

        lbldateEdition.setText("Date d'édition:");

        lblediteur.setText("Editeur: ");

        comboEditeur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEditeur.setPreferredSize(new java.awt.Dimension(165, 20));

        ajouterEditeur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajouterEditeur.setText("+");
        ajouterEditeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterEditeurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditionLayout = new javax.swing.GroupLayout(panelEdition);
        panelEdition.setLayout(panelEditionLayout);
        panelEditionLayout.setHorizontalGroup(
            panelEditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditionLayout.createSequentialGroup()
                        .addComponent(lbldateEdition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooserDateEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEditionLayout.createSequentialGroup()
                        .addComponent(lblediteur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboEditeur, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajouterEditeur)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditionLayout.setVerticalGroup(
            panelEditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEditeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterEditeur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldateEdition)
                    .addComponent(chooserDateEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panelDetailsLayout = new javax.swing.GroupLayout(panelDetails);
        panelDetails.setLayout(panelDetailsLayout);
        panelDetailsLayout.setHorizontalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetailsLayout.createSequentialGroup()
                                .addComponent(panelPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDetailsLayout.createSequentialGroup()
                                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetailsLayout.createSequentialGroup()
                                        .addComponent(panelTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(panelEdition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(panelLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addComponent(panelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelResume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetailsLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(panelAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDetailsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelTVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDetailsLayout.setVerticalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addComponent(panelLangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(panelEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTheme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(panelAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelResume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(panelTVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPrix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));
        panelImage.setMinimumSize(new java.awt.Dimension(500, 100));
        panelImage.setPreferredSize(new java.awt.Dimension(500, 100));

        javax.swing.GroupLayout panelAffichageImageLayout = new javax.swing.GroupLayout(panelAffichageImage);
        panelAffichageImage.setLayout(panelAffichageImageLayout);
        panelAffichageImageLayout.setHorizontalGroup(
            panelAffichageImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        panelAffichageImageLayout.setVerticalGroup(
            panelAffichageImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAffichageImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addComponent(panelAffichageImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelFichier.setBorder(javax.swing.BorderFactory.createTitledBorder("Fichier"));

        javax.swing.GroupLayout panelFichierLayout = new javax.swing.GroupLayout(panelFichier);
        panelFichier.setLayout(panelFichierLayout);
        panelFichierLayout.setHorizontalGroup(
            panelFichierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFichierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chooserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        panelFichierLayout.setVerticalGroup(
            panelFichierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelISBN.setBorder(javax.swing.BorderFactory.createTitledBorder("ISBN"));

        lblNumISBN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumISBN.setText("Numéro ISBN ");

        lblISBN.setText("ISBN: ");

        txtISBN.setColumns(20);
        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelISBNLayout = new javax.swing.GroupLayout(panelISBN);
        panelISBN.setLayout(panelISBNLayout);
        panelISBNLayout.setHorizontalGroup(
            panelISBNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelISBNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelISBNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelISBNLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblNumISBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelISBNLayout.createSequentialGroup()
                        .addComponent(lblISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelISBNLayout.setVerticalGroup(
            panelISBNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelISBNLayout.createSequentialGroup()
                .addComponent(lblNumISBN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelISBNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelISBNLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblISBN))))
        );

        javax.swing.GroupLayout panelLivreLayout = new javax.swing.GroupLayout(panelLivre);
        panelLivre.setLayout(panelLivreLayout);
        panelLivreLayout.setHorizontalGroup(
            panelLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLivreLayout.createSequentialGroup()
                        .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLivreLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLivreLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLivreLayout.setVerticalGroup(
            panelLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLivreLayout.createSequentialGroup()
                        .addComponent(panelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );

        panelBoutonsLivre.setBorder(javax.swing.BorderFactory.createTitledBorder("Boutons"));
        panelBoutonsLivre.setLayout(new java.awt.GridBagLayout());

        jButtonInserer.setText("Insérer");
        jButtonInserer.setAlignmentX(0.5F);
        jButtonInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsererActionPerformed(evt);
            }
        });
        panelBoutonsLivre.add(jButtonInserer, new java.awt.GridBagConstraints());

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        panelBoutonsLivre.add(jButtonModifier, new java.awt.GridBagConstraints());

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });
        panelBoutonsLivre.add(jButtonSupprimer, new java.awt.GridBagConstraints());

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });
        panelBoutonsLivre.add(jButtonAfficher, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLivre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBoutonsLivre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 970, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelBoutonsLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void txtsousTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsousTitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsousTitreActionPerformed

    private void txttitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttitreActionPerformed

    private void ajouterThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterThemeActionPerformed

    private void ajouterSousThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterSousThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterSousThemeActionPerformed

    private void ajouterAuteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterAuteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterAuteurActionPerformed

    private void txtstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstockActionPerformed

    private void txtprixHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprixHTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprixHTActionPerformed

    private void txtTVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTVAActionPerformed

    private void comboLangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLangueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLangueActionPerformed

    private void ajouterLangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterLangueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterLangueActionPerformed

    private void ajouterEditeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterEditeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterEditeurActionPerformed

    private void jButtonInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsererActionPerformed

        try {

            livre.setIsbn(Integer.parseInt(txtISBN.getText()));
            livre.setIdLangue(comboLangue.getSelectedIndex());
            livre.setIdEditeur(comboEditeur.getSelectedIndex());
            chooserDateEditionsetDateEdition(chooserDate.getDate());
            livre.setTitre(txttitre.getText());
            livre.setSousTitre(txtsousTitre.getText());
            livre.setResume(txtresume.getText());
            livre.setStock(Integer.parseInt(txtstock.getText()));
            livre.setPrix(Float.parseFloat(txtprixHT.getText()));
            livre.setTva(Float.parseFloat(txtTVA.getText()));
            livre.getActif();

            livre.setTheme(combotheme.getName());
            livre.setSousTheme(combosstheme.getName());

        } catch (Exception ex) {
            Logger.getLogger(JFLivre.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            livre.inserer();
            afficherTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFLivre.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFLivre.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(JFLivre.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("Données insérées.");

    }//GEN-LAST:event_jButtonInsererActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        try {
            livre.setIsbn(Integer.parseInt(txtISBN.getText()));
            livre.setIdLangue(comboLangue.getSelectedIndex());
            livre.setIdEditeur(comboEditeur.getSelectedIndex());
            chooserDateEditionsetDateEdition(chooserDate.getDate());
            livre.setTitre(txttitre.getText());
            livre.setSousTitre(txtsousTitre.getText());
            livre.setResume(txtresume.getText());
            livre.setTheme(combotheme.getName());
            livre.setSousTheme(combosstheme.getName());
            livre.setStock(Integer.parseInt(txtstock.getText()));
            livre.setPrix(Float.parseFloat(txtprixHT.getText()));
            livre.setTva(Float.parseFloat(txtTVA.getText()));
            livre.getActif();

            System.out.println("id: " + Integer.parseInt(txtISBN.getText()));
            livre.modifier(Integer.parseInt(txtISBN.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {
            Logger.getLogger(JFLivre.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("Données modifiées.");

    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        try {
            livre.supprimer(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {
            Logger.getLogger(JFLivre.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("Données supprimées.");

    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherActionPerformed
        try {
            afficherTable();
        } catch (Exception ex) {
            Logger.getLogger(JFLivre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAfficherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterAuteur;
    private javax.swing.JButton ajouterEditeur;
    private javax.swing.JButton ajouterLangue;
    private javax.swing.JButton ajouterSousTheme;
    private javax.swing.JButton ajouterTheme;
    private com.toedter.calendar.JDateChooser chooserDateEdition;
    private javax.swing.JFileChooser chooserImage;
    private javax.swing.JComboBox comboAuteur;
    private javax.swing.JComboBox comboEditeur;
    private javax.swing.JComboBox comboLangue;
    private javax.swing.JComboBox combosstheme;
    private javax.swing.JComboBox combotheme;
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonInserer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel lblAuteur;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblNumISBN;
    private javax.swing.JLabel lblSousTheme;
    private javax.swing.JLabel lblTVA;
    private javax.swing.JLabel lblTheme;
    private javax.swing.JLabel lbldateEdition;
    private javax.swing.JLabel lblediteur;
    private javax.swing.JLabel lbllangue;
    private javax.swing.JLabel lblprixHT;
    private javax.swing.JLabel lblresume;
    private javax.swing.JLabel lblsousTitre;
    private javax.swing.JLabel lblstock;
    private javax.swing.JLabel lbltitre;
    private javax.swing.JPanel panelAffichageImage;
    private javax.swing.JPanel panelAuteur;
    private javax.swing.JPanel panelBoutonsLivre;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JPanel panelEdition;
    private javax.swing.JPanel panelFichier;
    private javax.swing.JPanel panelISBN;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panelLangue;
    private javax.swing.JPanel panelLivre;
    private javax.swing.JPanel panelPrix;
    private javax.swing.JPanel panelResume;
    private javax.swing.JPanel panelStock;
    private javax.swing.JPanel panelTVA;
    private javax.swing.JPanel panelTheme;
    private javax.swing.JPanel panelTitre;
    private javax.swing.JScrollPane scpresume;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTVA;
    private javax.swing.JTextField txtprixHT;
    private javax.swing.JTextArea txtresume;
    private javax.swing.JTextField txtsousTitre;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txttitre;
    // End of variables declaration//GEN-END:variables
}
