package essai2;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class IF_Langue extends javax.swing.JInternalFrame {

    private Langue langue=new Langue();
    private Fen fen;
    
    
    public IF_Langue() {
        initComponents();
    }

    public void setFen(Fen fen) {
        this.fen = fen;
    }

    public JLabel getTxtId() {
        return txtId;
    }

    public JTextField getTxtLangue() {
        return txtLangue;
    }
    
    

    public void afficherTable() throws SQLException, Exception {

        try {
            String req = "SELECT idLangue AS ID, nomLangue AS LANGUE,actifLangue AS ACTIF"                    
                       + " from Langue order by nomLangue";
            ResultSet rs = langue.selectionner(req);
            fen.getIfALangue().getjTableLangue().setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChampsLangue = new javax.swing.JPanel();
        lblnom = new javax.swing.JLabel();
        txtLangue = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        panelBoutons = new javax.swing.JPanel();
        jButtonInserer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonAfficher = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("LANGUE");

        panelChampsLangue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Langue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelChampsLangue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnom.setText("Langue: ");
        panelChampsLangue.add(lblnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        txtLangue.setColumns(20);
        panelChampsLangue.add(txtLangue, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        labelId.setText("Id:");
        panelChampsLangue.add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelChampsLangue.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 30, 20));

        panelBoutons.setBorder(javax.swing.BorderFactory.createTitledBorder("Boutons"));
        panelBoutons.setLayout(new java.awt.GridBagLayout());

        jButtonInserer.setText("Insérer");
        jButtonInserer.setAlignmentX(0.5F);
        jButtonInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsererActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonInserer, new java.awt.GridBagConstraints());

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonModifier, new java.awt.GridBagConstraints());

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonSupprimer, new java.awt.GridBagConstraints());

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonAfficher, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBoutons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelChampsLangue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChampsLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsererActionPerformed

        try {
            langue.setLangue(txtLangue.getText());
            langue.getActif();

        } catch (Exception ex) {
            
        }

        try {
            langue.inserer();
            afficherTable();
        } catch (ClassNotFoundException ex) {
            
        } catch (SQLException ex) {
           
        } catch (Exception ex) {
            
        }

        System.out.println("Données insérées.");

    }//GEN-LAST:event_jButtonInsererActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        try {
            langue.setLangue(txtLangue.getText());
            langue.getActif();
            System.out.println("id: " + Integer.parseInt(txtId.getText()));
            langue.modifier(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {
           
        }

        System.out.println("Données modifiées.");

    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        try {
            langue.supprimer(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {
            
        }

        System.out.println("Données supprimées.");

    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherActionPerformed
        try {
            afficherTable();
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jButtonAfficherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonInserer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel lblnom;
    private javax.swing.JPanel panelBoutons;
    private javax.swing.JPanel panelChampsLangue;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtLangue;
    // End of variables declaration//GEN-END:variables
}
