/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package essai2;

/**
 *
 * @author HP
 */
public class IF_SSTheme extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_SSTheme
     */
    public IF_SSTheme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTheme = new javax.swing.JPanel();
        lblTheme = new javax.swing.JLabel();
        combotheme = new javax.swing.JComboBox();
        lblSousTheme = new javax.swing.JLabel();
        ajouterTheme = new javax.swing.JButton();
        txtSSTheme = new javax.swing.JTextField();
        panelBoutons = new javax.swing.JPanel();
        jButtonInserer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonAfficher = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("SOUS-THEME");

        panelTheme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sous-Thème", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblTheme.setText("Thème:");

        combotheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSousTheme.setText("Sous-thème:");

        ajouterTheme.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajouterTheme.setText("+");
        ajouterTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThemeLayout = new javax.swing.GroupLayout(panelTheme);
        panelTheme.setLayout(panelThemeLayout);
        panelThemeLayout.setHorizontalGroup(
            panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelThemeLayout.createSequentialGroup()
                        .addComponent(lblTheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combotheme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThemeLayout.createSequentialGroup()
                        .addComponent(lblSousTheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSSTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ajouterTheme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelThemeLayout.setVerticalGroup(
            panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSousTheme)
                    .addComponent(txtSSTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTheme)
                    .addComponent(combotheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        panelBoutons.setBorder(javax.swing.BorderFactory.createTitledBorder("Boutons"));
        panelBoutons.setLayout(new java.awt.GridBagLayout());

        jButtonInserer.setText("Insérer");
        jButtonInserer.setAlignmentX(0.5F);
        jButtonInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsererActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonInserer, new java.awt.GridBagConstraints());

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonModifier, new java.awt.GridBagConstraints());

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonSupprimer, new java.awt.GridBagConstraints());

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonAfficher, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterThemeActionPerformed

    private void jButtonInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsererActionPerformed

        try {
            editeur.setNom(txtnom.getText());
            editeur.setNoRue(txtPrenom.getText());
            editeur.setRue(txtDateNaissance.getText());
            editeur.setCodePostal(txtcodePostal.getText());
            editeur.setVille(txtLieuNaissance.getText());
            editeur.setPays(txtpays.getText());
            editeur.setTelephone(txttel.getText());
            editeur.setEmail(txtemail.getText());
            editeur.getActif();

        } catch (Exception ex) {

        }

        try {
            editeur.inserer();
            afficherTable();
        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        } catch (Exception ex) {

        }

        System.out.println("Données insérées.");
    }//GEN-LAST:event_jButtonInsererActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        try {
            editeur.setNom(txtnom.getText());
            editeur.setNoRue(txtPrenom.getText());
            editeur.setRue(txtDateNaissance.getText());
            editeur.setCodePostal(txtcodePostal.getText());
            editeur.setVille(txtLieuNaissance.getText());
            editeur.setPays(txtpays.getText());
            editeur.setTelephone(txttel.getText());
            editeur.setEmail(txtemail.getText());
            editeur.getActif();
            System.out.println("id: " + Integer.parseInt(txtId.getText()));
            editeur.modifier(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {

        }

        System.out.println("Données modifiées.");
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        try {
            editeur.supprimer(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {

        }

        System.out.println("Données supprimées.");
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherActionPerformed
        try {
            afficherTable();
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButtonAfficherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterTheme;
    private javax.swing.JComboBox combotheme;
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonInserer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel lblSousTheme;
    private javax.swing.JLabel lblTheme;
    private javax.swing.JPanel panelBoutons;
    private javax.swing.JPanel panelTheme;
    private javax.swing.JTextField txtSSTheme;
    // End of variables declaration//GEN-END:variables
}
