package essai2;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class IF_Theme extends javax.swing.JInternalFrame {

    private Theme theme=new Theme();
    private Fen fen;
    
    public IF_Theme() {
        initComponents();
    }

    public void setFen(Fen fen) {
        this.fen = fen;
    }

    public JLabel getTxtId() {
        return txtId;
    }
        
    public JTextField getTxtTheme() {
        return txtTheme;
    }
    
    public void afficherTable() throws SQLException, Exception {

        try {
            String req = "SELECT idTheme AS ID, nomTheme AS THEME,actifTheme AS ACTIF"                    
                       + " from Theme order by nomTheme";
            ResultSet rs = theme.selectionner(req);
            fen.getIfATheme().getjTableTheme().setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoutons = new javax.swing.JPanel();
        jButtonInserer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonAfficher = new javax.swing.JButton();
        panelTheme = new javax.swing.JPanel();
        lblTheme = new javax.swing.JLabel();
        lblSousTheme = new javax.swing.JLabel();
        ajouterSSTheme = new javax.swing.JButton();
        txtTheme = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Thème");

        panelBoutons.setBorder(javax.swing.BorderFactory.createTitledBorder("Boutons"));
        panelBoutons.setLayout(new java.awt.GridBagLayout());

        jButtonInserer.setText("Insérer");
        jButtonInserer.setAlignmentX(0.5F);
        jButtonInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsererActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonInserer, new java.awt.GridBagConstraints());

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonModifier, new java.awt.GridBagConstraints());

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonSupprimer, new java.awt.GridBagConstraints());

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });
        panelBoutons.add(jButtonAfficher, new java.awt.GridBagConstraints());

        panelTheme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thème", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblTheme.setText("Thème:");

        lblSousTheme.setText("Sous-thème:");

        ajouterSSTheme.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajouterSSTheme.setText("+");
        ajouterSSTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterSSThemeActionPerformed(evt);
            }
        });

        lblId.setText("Id:");

        javax.swing.GroupLayout panelThemeLayout = new javax.swing.GroupLayout(panelTheme);
        panelTheme.setLayout(panelThemeLayout);
        panelThemeLayout.setHorizontalGroup(
            panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblId)
                    .addComponent(lblSousTheme)
                    .addComponent(lblTheme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterSSTheme)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelThemeLayout.setVerticalGroup(
            panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTheme)
                    .addComponent(txtTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSousTheme)
                    .addComponent(ajouterSSTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterSSThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterSSThemeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ajouterSSThemeActionPerformed

    private void jButtonInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsererActionPerformed

        try {
            theme.setTheme(txtTheme.getText());
            theme.getActif();

        } catch (Exception ex) {
            
        }

        try {
            theme.inserer();
            afficherTable();
        } catch (ClassNotFoundException ex) {
            
        } catch (SQLException ex) {
           
        } catch (Exception ex) {
            
        }

        System.out.println("Données insérées.");
    }//GEN-LAST:event_jButtonInsererActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        try {
            theme.setTheme(txtTheme.getText());
            theme.getActif();
            System.out.println("id: " + Integer.parseInt(txtId.getText()));
            theme.modifier(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {
           
        }

        System.out.println("Données modifiées.");

    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        try {
            theme.supprimer(Integer.parseInt(txtId.getText()));
            afficherTable();
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } catch (Exception ex) {

        }

        System.out.println("Données supprimées.");
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherActionPerformed
        try {
            afficherTable();
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButtonAfficherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterSSTheme;
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonInserer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblSousTheme;
    private javax.swing.JLabel lblTheme;
    private javax.swing.JPanel panelBoutons;
    private javax.swing.JPanel panelTheme;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtTheme;
    // End of variables declaration//GEN-END:variables
}
